data:
  path: /Users/charaka/Desktop/University/Msc Machine Learning & Data Science/Masters Project/football-data
  division_names:
    - E0
    - E1
    - SP1
  years:
    - 2015-2016
    - 2016-2017
    - 2017-2018
    - 2018-2019
    - 2019-2020
    - 2020-2021
    - 2021-2022
    - 2022-2023