data:
  path: /Users/charaka/Desktop/University/Msc Machine Learning & Data Science/Masters Project/football-data
  division_names:
    - E0
  years:
    - 2015-2016
    - 2016-2015
    - 2017-2016
    - 2018-2017
    - 2019-2018
    - 2020-2019
    - 2021-2022
    - 2022-2023